esphome:
  name: tcl-ac

esp8266:
  board: esp01_1m

logger:
  level: WARN
  baud_rate: 0
  
api:
  encryption:
    key: "!!! your Base4 Key here !!!"

ota:
  platform: esphome
  password: !secret ota_pwd

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: True

# Optional #
#  manual_ip:
#    static_ip: 192.168.1.100
#    gateway: 192.168.1.1
#    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "tcl-ac Fallback Hotspot"
    password: !secret wifi_password

captive_portal:
    
uart:
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 9600
  parity: EVEN
  data_bits: 8
  stop_bits: 1

external_components:
  - source: github://phazoxNL/esphome-tcl-ac
    components: [ tcl_ac ]

climate:
  - platform: tcl_ac
    id: tcl_ac
    name: "TCL AC"
    beeper: false
    display: true
    vertical_direction: "down"

switch:
  - platform: template
    name: "TCL Beeper"
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    lambda: |-
      return id(tcl_ac).get_beeper_state();
    turn_on_action:
      - lambda: |-
          id(tcl_ac).set_beeper_state(true);
    turn_off_action:
      - lambda: |-
          id(tcl_ac).set_beeper_state(false);

  - platform: template
    name: "TCL Display"
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    lambda: |-
      return id(tcl_ac).get_display_state();
    turn_on_action:
      - lambda: |-
          id(tcl_ac).set_display_state(true);
    turn_off_action:
      - lambda: |-
          id(tcl_ac).set_display_state(false);
